var SOBE = SOBE || {};

SOBE.images = [
    "alain_colmerauer.jpg",
    "alan_kay.jpg",
    "bjarne_strousup.jpg",
    "brendan_eich.jpg",
    "brian_kerninghan.jpg",
    "cleve_moler.jpg",
    "dennis_ritchie.jpg",
    "donald_knuth.jpg",
    "Edsger_Wybe_Dijkstra.jpg",
    "grace_hopper.jpg",
    "guido_von_rossum.jpg",
    "james_gosling.jpg",
    "jean_ichbiah.jpg",
    "joe_armstrong.jpg",
    "john_backus.jpg",
    "john_carmack.jpg",
    "john_mccarthy.jpg",
    "jose_valheem.jpg",
    "kenneth_iverson.jpg",
    "larry_wall.jpg",
    "martin_odersky.jpg",
    "matz.jpg",
    "mike_williams.jpg",
    "neil_pappalardo.jpg",
    "rasmus_lerfdorf.jpg",
    "richard_stalmman.jpg",
    "roberto_ierusalimschy.jpg",
    "robert_verding.jpg",
    "rob_pike.jpg",
    "seymour_papert.jpg",
    "stephen_wolfram.jpg",
    "tim_sweeney.jpg"
]
